#docker-compose -p fwtl -f "docker-compose.yaml" up -d --build
#docker-compose -p fwtl -f "docker-compose.yaml" -f "docker-compose.local.yaml" up -d --build
#docker cp .env.docker FWTL-telegram-api-server:/app/.env.docker
version: "3.4"

services:
  seq:
    image: datalust/seq:latest
    container_name: "FWTL-seq"
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - FWTL-data:/data
    networks:
      - backend
  sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: "FWTL-sql"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "!QAZ2wsx"
    volumes:
      - FWTL-sql-data:/var/opt/mssql
    networks:
      - backend
  telegram-api-server:
    image: xtrime/telegram-api-server:latest
    container_name: FWTL-telegram-api-server
    restart: unless-stopped
    ports:
      - "127.0.0.1:9503:9503"
    volumes:
      - "FWTL-sessions:/app/sessions"
      - ./.env.docker:/app/.env.docker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "FWTL-rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - FWTL-data:/var/lib/rabbitmq
    networks:
      - backend
  redis:
    image: redis:alpine
    container_name: "FWTL-redis"
    ports:
      - "6379:6379"
    volumes:
      - FWTL-data:/var/lib/redis/data
    networks:
      - backend
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: "FWTL-redisinsight"
    ports:
      - "8005:8001"
    networks:
      - backend
  eventStore:
    image: docker.pkg.github.com/eventstore/eventstore/eventstore:20.6.1-alpha.0.69.1-buster-slim
    container_name : "FWTL-eventStore"
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_DB=/var/lib/eventstore-data
      - EVENTSTORE_INDEX=/var/lib/eventstore-index
      - EVENTSTORE_LOG=/var/log/eventstore
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_DEV=True
      - EVENTSTORE_INSECURE=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: FWTL-eventstore-volume-data
        target: /var/lib/eventstore-data
      - type: volume
        source: FWTL-eventstore-volume-index
        target: /var/lib/eventstore-index
      - type: volume
        source: FWTL-eventstore-volume-logs
        target: /var/log/eventstore
    networks: 
      - backend

volumes:
  FWTL-sql-data:
  FWTL-data:
  FWTL-sessions:
  FWTL-eventstore-volume-data:
  FWTL-eventstore-volume-ca:
  FWTL-eventstore-volume-index:
  FWTL-eventstore-volume-logs:

networks:
  backend:
  frontend:
