version: "3"
#docker-compose -p fwtl -f "docker-compose.yaml" up -d --build

services:
  seq:
    image: datalust/seq:latest
    container_name: "FWTL-seq"
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - FWTL-data:/data
    networks:
      - backend
  sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: "FWTL-sql"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "KQlqqjercDE7d4YSF3O"
    volumes:
      - FWTL-sql-data:/var/opt/mssql
    networks:
      - backend

volumes:
  FWTL-sql-data:
  FWTL-data:

networks:
  backend:
  frontend:
