#docker-compose -p fwtl -f "docker-compose.yaml" up -d --build
#docker-compose -p fwtl -f "docker-compose.yaml" -f "docker-compose.local.yaml" up -d --build
#docker cp .env.docker FWTL-telegram-api-server:.env.docker

version: "3.4"

services:
  seq:
    image: datalust/seq:latest
    container_name: "FWTL-seq"
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - FWTL-data:/data
    networks:
      - backend
  # sql:
  #   image: mcr.microsoft.com/mssql/server:2017-latest
  #   container_name: "FWTL-sql"
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     SA_PASSWORD: "!QAZ2wsx"
  #   volumes:
  #     - FWTL-sql-data:/var/opt/mssql
  #   networks:
  #     - backend
  telegram-api-server:
    image: xtrime/telegram-api-server:latest
    container_name: FWTL-telegram-api-server
    restart: unless-stopped
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - "127.0.0.1:9503:9503"
    volumes:
      - C:/Projects/FWTLAuth/.env.docker:/app/sessions/.env.docker
    #working_dir: /app-host-link
    depends_on:
      - mysql
  mysql:
    image: mariadb:10.5
    container_name: FWTL-mysql
    ports:
      - "127.0.0.1:9507:3306"
    volumes:
      - FWTL-mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "FWTL-rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - FWTL-data:/var/lib/rabbitmq
    networks:
      - backend
  redis:
    image: redis:alpine
    container_name: "FWTL-redis"
    ports:
      - "6379:6379"
    volumes:
      - FWTL-data:/var/lib/redis/data
    networks:
      - backend
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: "FWTL-redisinsight"
    ports:
      - "8005:8001"
    networks:
      - backend
  # mongo:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: rootpassword
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - FWTL-mongo-data:/data/db
  eventStore:
    image: eventstore/eventstore:latest
    container_name : "FWTL-eventStore"
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INT_TCP_PORT=1112
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INT_HTTP_PORT=2112
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
    ports:
      - "1112:1112"
      - "1113:1113"
      - "2112:2112"
      - "2113:2113"
    volumes :
      - FWTL-eventStore-data:/var/lib/eventstore/data
    networks :
      - backend

volumes:
  FWTL-sql-data:
  FWTL-data:
  FWTL-sessions:
  FWTL-mongo-data:
  FWTL-eventStore-data:
  FWTL-mysql:
  
networks:
  backend:
  frontend:
