apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-deployment-{{ .Values.accountId }}
spec:
  selector:
    matchLabels:
      app: telegram-{{ .Values.accountId }}
  replicas: 1
  template:
    metadata:
      labels:
        app: telegram-{{ .Values.accountId }}
    spec:
      containers:
        - name: telegram
          image: xtrime/telegram-api-server:latest
          volumeMounts:
            - name: config-volume-{{ .Values.accountId }}
              mountPath: /app/sessions/.env.docker
              subPath: .env.docker
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 9503
      volumes:
        - name: config-volume-{{ .Values.accountId }}
          configMap:
            name: telegram-config-{{ .Values.accountId }}