apiVersion: v1
kind: Service
metadata:
  name: telegram-service-{{ .Values.accountId }}
spec:
  selector:
    app: telegram-{{ .Values.accountId }}
  ports:
  - name: http
    port: 9503
    protocol: TCP